table dim_date

	column date
		dataType: dateTime
		isKey
		formatString: Short Date
		summarizeBy: none
		sourceColumn: date

	column week_start
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: week_start

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: int64
		summarizeBy: none
		sourceColumn: quarter

	column month
		dataType: int64
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		summarizeBy: none
		sourceColumn: month_name

	column week_number
		dataType: int64
		summarizeBy: none
		sourceColumn: week_number

	column year_week
		dataType: string
		summarizeBy: none
		sourceColumn: year_week

	partition dim_date-dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "dim_date.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"date", type date},
				        {"week_start", type date},
				        {"year", Int64.Type},
				        {"quarter", Int64.Type},
				        {"month", Int64.Type},
				        {"month_name", type text},
				        {"week_number", Int64.Type},
				        {"year_week", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
