table model_performance

	column model
		dataType: string
		summarizeBy: none
		sourceColumn: model

	column algorithm
		dataType: string
		summarizeBy: none
		sourceColumn: algorithm

	column target
		dataType: string
		summarizeBy: none
		sourceColumn: target

	column metric_type
		dataType: string
		summarizeBy: none
		sourceColumn: metric_type

	column metric_name
		dataType: string
		summarizeBy: none
		sourceColumn: metric_name

	column metric_value
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: metric_value

	partition model_performance-model_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "model_performance.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"model", type text},
				        {"algorithm", type text},
				        {"target", type text},
				        {"metric_type", type text},
				        {"metric_name", type text},
				        {"metric_value", type number}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
