table sales_forecast

	column week_start
		dataType: dateTime
		isKey
		formatString: Short Date
		summarizeBy: none
		sourceColumn: week_start

	column actual_revenue
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: actual_revenue

	column predicted_revenue
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: predicted_revenue

	column prediction_error
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: prediction_error

	column model_name
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column is_future
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_future

	partition sales_forecast-sales_forecast = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "sales_forecast.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"week_start", type date},
				        {"actual_revenue", type number},
				        {"predicted_revenue", type number},
				        {"prediction_error", type number},
				        {"model_name", type text},
				        {"is_future", type logical}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
